sonar.projectKey=TandaPlus
sonar.projectName=TandaPlus
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=sqp_b762cc9c05132df3b5563c73238ba1d3cbc9673f