sonar.projectKey=TandaPlus
sonar.projectName=TandaPlus
sonar.projectVersion=1.0

#Oropeza Yepiz Cristian Efraín
sonar.sources=lib
sonar.tests=test

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=sqp_9fca2409721d5239ee70f7c2ea7a9144cdd9c0c3
